### ISSUE TITLE
Add extraFields to a BoundBox 

### ISSUE THREAD

**Issue by flavienlaurent** [stephanenicolas/boundbox#4] opened 2013-09-23 12:19 UTC
UPDATE --- 
The thread has been renamed. On Android, we use stub Android jars to compile an app, and those stubs only contain method signatures (their bodies all send the "Stub !" exception), and no fields. So it is interesting to be able to add fields explicitly to a BoundBox class so that, when a call to the BoundBox setters/getters will be made, it will be resolved at runtime by reflection and the field will be accessed for real.
UPDATE --- 

The code

```
@BoundBox(boundClass=TextView.class)
BoundBoxOfTextView boundBoxOfTextView;
```

BoundBoxOfTextView class isn't well generated:
- import statement conflict

```
import android.text.Editable.Factory;
import android.text.Layout;
import android.text.Spannable.Factory;
```
- private fields are missing. For example, TextView contains 

```
private ArrayList<TextWatcher> mListeners;
```

and there is no method to access to it in BoundBoxOfTextView

**Comment by stephanenicolas** [comment] 2013-09-23 16:24
Woopss. Looks like a miss ;)

Thank you very much for reporting these bugs. It would be very nice to have
gists reproducing the problem _but_ without using android classes.

I mean having a dependency on Android would be too heavy, even just for
testing.

We could isolate what's going wrong and create small test cases for each
problem. For instance a generics field seems to be a source of problem.

For the import conflict I still don't see clearly what's wrong and even
less what the problem can be.

Stephane
Le 23 sept. 2013 14:19, "Flavien Laurent" notifications@github.com a
écrit :

**Comment by flavienlaurent** [comment] 2013-09-23 17:09
You're welcome :)

I don't think it's because of generics.
I wrote a simple test in library-integration-tests: you can take a look on https://gist.github.com/flavienlaurent/6673763

**Comment by stephanenicolas** [comment] 2013-09-24 06:54
for imports, I found out that the problem comes from javawriter. it compresses types by default and doesn't handle very well conflicting imports.

see https://github.com/square/javawriter/pull/24#write_bucket_749

**Comment by stephanenicolas** [comment] 2013-09-24 07:14
see issue #2

**Comment by flavienlaurent** [comment] 2013-09-24 08:04
Ok for import statements conflict but did you fixed missing private fields issue?

**Comment by stephanenicolas** [comment] 2013-09-24 08:40
For import statements, I initiated a pull request in java writer. With this fix, everything is going well for TextView. 
(apart of the private field issue you mention. Please in the future, try to issue one bug per bug/feature request.)

**Comment by stephanenicolas** [comment] 2013-09-24 09:00
About the missing field. I think I got the explanation. I could reproduce the "bug" locally. It's indeed not a bug to my mind. What happens is that the android jars that are used for compilation are indeed android jars containing only methods that send the "Stub !" exception. They just provide signatures of all methods of android classes but don't actually contain any field of those classes.

Therefore, due to full android classes being unavailable at runtime, it will not be possible to get their fields. All fields of _your own_ classes are available, as well as their super class, but, whenver you use an android class, you won't have access to anything other than methods.

**Comment by flavienlaurent** [comment] 2013-09-24 09:13
I suspected this problem ... It could be interesting to add extra informations in annotation to force specific field to be bound boxed.

Let's imagine

```
@BoundBox(
    boundClass=TextView.class,
    boundFields={
        @BoundBoxField(fieldClass=ArrayList.class, fieldName="mListeners"),
        @BoundBoxField(fieldClass=TextPaint.class, fieldName="mTextPaint"),
    }
)
```

What do you think?

**Comment by stephanenicolas** [comment] 2013-09-24 09:32
ok for extraBoundFields. Do you feel like coding it ?

I am really eager to see java writer released with optional type
compression, before that we can't release anything. This might give us some
time to develop better features.

2013/9/24 Flavien Laurent notifications@github.com

> I suspected this problem ... It could be interesting to add extra
> informations in annotation to force specific field to be bound boxed.
> 
> Let's imagine
> 
> @BoundBox(
>     boundClass=TextView.class,
>     boundFields={
>         @BoundBoxField(fieldClass=ArrayList.class, fieldName="mListeners"),
>         @BoundBoxField(fieldClass=TextPaint.class, fieldName="mTextPaint"),
>     }
> )
> 
> What do you think?
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/stephanenicolas/boundbox/issues/4#issuecomment-24987221
> .

## 

Stéphane _NICOLAS_,
_OCTO Technology_
Développeur & Consultant Android / Java
..........................................................
50, Avenue des Champs-Elysées
75008 Paris
+33 (0)6.26.32.34.09
www.octo.com - mobilite.octo.com
blog.octo.com - www.usievents.com
...........................................................

**Comment by flavienlaurent** [comment] 2013-09-24 09:45
yes, I can focus on this feature.

**Comment by stephanenicolas** [comment] 2013-09-24 12:31
Wonderful. On my side, I will focus on adding support for inner classes,
and generate a relevant javadoc, and wait for Javawriter's new release and
its integration.

I should get it within 15 days, at most. Except for javawriter, as it will
depend on their side.

S.

2013/9/24 Flavien Laurent notifications@github.com

> yes, I can focus on this feature.
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/stephanenicolas/boundbox/issues/4#issuecomment-24989601
> .

## 

Stéphane _NICOLAS_,
_OCTO Technology_
Développeur & Consultant Android / Java
..........................................................
50, Avenue des Champs-Elysées
75008 Paris
+33 (0)6.26.32.34.09
www.octo.com - mobilite.octo.com
blog.octo.com - www.usievents.com
...........................................................

**Comment by flavienlaurent** [comment] 2013-09-24 12:56
Ok.

Some advices on how to see logs?
Can you provide your codestyle?

**Comment by stephanenicolas** [comment] 2013-09-24 14:15
mvn clean install will show logs.
I think they is a tab in eclipse's console output that displays errors and
logs as well.

I don't debug, I just trace. If you find a better way, I would use it.

S.

2013/9/24 Flavien Laurent notifications@github.com

> Ok. Some advices on how to debug the annotation processor and how to see
> logs?
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/stephanenicolas/boundbox/issues/4#issuecomment-25000068
> .

## 

Stéphane _NICOLAS_,
_OCTO Technology_
Développeur & Consultant Android / Java
..........................................................
50, Avenue des Champs-Elysées
75008 Paris
+33 (0)6.26.32.34.09
www.octo.com - mobilite.octo.com
blog.octo.com - www.usievents.com
...........................................................

**Comment by flavienlaurent** [comment] 2013-09-24 15:58
I just finished to code a basic implementation of this feature. Do you known how to test this feature? I wrote test in boundbox-library and boundbox-android-sample-tests but I have no idea how to test it in boundbox-library-integration-tests.

Actually, I've this test

```
package org.boundbox.sample;

import org.boundbox.BoundBox;
import org.boundbox.BoundBoxField;
import org.junit.Before;
import org.junit.Test;

public class ExtraFieldTest {

    private FieldTestClassB fieldTestClassB;
    @BoundBox(
            boundClass = FieldTestClassB.class,
            extraBoundFields = {
                @BoundBoxField(
                        fieldName =  "fakeField1",
                        fieldClass = String.class
                )
            }
    )
    private BoundBoxOfFieldTestClassB boundBoxOfB;

    @Before
    public void setup() {
        fieldTestClassB = new FieldTestClassB();
        boundBoxOfB = new BoundBoxOfFieldTestClassB(fieldTestClassB);
    }

    @Test
    public void test_read_access_to_field() {
        boundBoxOfB.boundBox_getFakeField1(); // <-- throws NoSuchFieldException obviously
    }
}
```

**Comment by stephanenicolas** [comment] 2013-09-24 16:37
In a unit test for the writer, you would check that the getters and setters
are present in the boundboxofX class (via reflection).
In a unit test for the processor, you would check that the FieldInfo
contains correct data for the extra field.

In an integration test you would test that the read access fails on a bound
class that doesn't contain the field.

Can you change extraBoundFields --> extraFields
My fault.

Nice ! Any pull request ready ?

Stéphane

2013/9/24 Flavien Laurent notifications@github.com

> I just finished to code a basic implementation of this feature. Do you
> known how to test this feature? I wrote test in boundbox-library,
> boundbox-android-sample-tests and boundbox-android-sample but I have no
> idea how to test it in boundbox-library-integration-tests.
> 
> Actually, I've this test
> 
> package org.boundbox.sample;
> 
> import org.boundbox.BoundBox;
> import org.boundbox.BoundBoxField;
> import org.junit.Before;
> import org.junit.Test;
> 
> public class ExtraFieldTest {
> 
> ```
> private FieldTestClassB fieldTestClassB;
> @BoundBox(
>         boundClass = FieldTestClassB.class,
>         extraBoundFields = {
>             @BoundBoxField(
>                     fieldName =  "fakeField1",
>                     fieldClass = String.class
>             )
>         }
> )
> private BoundBoxOfFieldTestClassB boundBoxOfB;
> 
> @Before
> public void setup() {
>     fieldTestClassB = new FieldTestClassB();
>     boundBoxOfB = new BoundBoxOfFieldTestClassB(fieldTestClassB);
> }
> 
> @Test
> public void test_read_access_to_field() {
>     boundBoxOfB.boundBox_getFakeField1(); // <-- throws NoSuchFieldException obviously
> }
> ```
> 
> }
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/stephanenicolas/boundbox/issues/4#issuecomment-25017829
> .

## 

Stéphane _NICOLAS_,
_OCTO Technology_
Développeur & Consultant Android / Java
..........................................................
50, Avenue des Champs-Elysées
75008 Paris
+33 (0)6.26.32.34.09
www.octo.com - mobilite.octo.com
blog.octo.com - www.usievents.com
...........................................................

**Comment by stephanenicolas** [comment] 2013-09-25 06:58
Please, when done, document the feature here : https://github.com/stephanenicolas/boundbox/wiki/Adding-extra-fields-to-a-boundbox

This page is already referenced/linked from [Wiki's main page](https://github.com/stephanenicolas/boundbox/wiki/) (section usage).

**Comment by flavienlaurent** [comment] 2013-09-25 08:40
Request pulled. Don't hesitate if you have a comment on something!
I wrote the documentation as well.

**Comment by stephanenicolas** [comment] 2013-09-25 18:08
https://github.com/stephanenicolas/boundbox/pull/7

**Closed as completed by stephanenicolas** 2013-09-25 18:08 UTC
Labels: enhancement
