### ISSUE TITLE
accessing static field in super class of non static inner class

### ISSUE THREAD

**Issue by flavienlaurent** [stephanenicolas/boundbox#18] opened 2013-10-04 10:35 UTC
A super class with a static field

```
public class SuperInnerClassWithStaticField {
    private static int c;
}
```

A class with non static inner class extending the super inner class just above

```
public class NonStaticInnerClassExtendingClassWithPrivateStaticFieldsTestClass {
    public class InnerClass extends SuperInnerClassWithStaticField {
        public int a;
    };
}
```

Result in 

```
public static int boundBox_super_InnerClass_getC() {
      try {
        Field field = boundClass.getSuperclass().getDeclaredField("c");
        field.setAccessible(true);
        return (Integer)  field.get(null);
      }
      catch( Exception e ) {
        throw new BoundBoxException(e);
      }
    }
```

which is wrong because `boundClass` is not static.

Headache in advance :)

I wrote an integration test for this one.

**Comment by stephanenicolas** [comment] 2013-10-05 10:29
You (and the compiler) are right : a non static inner class can't have any static methods (nor static fields nor static inner classes). 

There should be 2 solutions here : 
- detect when an inner class is non static and then access it's static inherited stuff via an objet
- replace the boundClass.getSuperclass() by the name of its super class directly. 

The second is very tempting by its elegance, the problem is that they are cases where it wouldn't work. For instance if the super class of the inner class is private, then the BoundBox won't be able to use its name inside the BoundBox scope. Therefore this solution would fail in some cases.

The first one should work and I think it makes sense. The name of the method could be kept static or not, both naming would be confusing in some extent.

**Comment by stephanenicolas** [comment] 2013-10-07 21:54
I opted for a model where InnerClass would offer a non static access to c. That is no optimal to access c as it is a static field. But it would be possible to create a BoundBox of SuperInnerClassWithStaticField if that's really what people want.

Funny enough, there are many ways to access that field with BoundBox : 
- create a bound box of InnerClass : get a non static access
- create a bound box of SuperInnerClassWithStaticField : get a static access

I need to update documentation to tell about this, with a descent schema. But issue should be solved.

**Comment by stephanenicolas** [comment] 2013-10-07 21:56
If you could write the integration test @flavienlaurent  that would be nice. Just to check the feature is added and fully working as you expected it.

**Comment by flavienlaurent** [comment] 2013-10-08 08:28
Ok. I will write it this day

**Comment by stephanenicolas** [comment] 2013-10-08 08:35
Thanks. If it works I let you close the issue. 

Personally, my next target is customizing boundbox package. I need that to compute visibility of classes used in BoundBoxes methods signatures.

**Closed as completed** 2013-10-15 17:52 UTC
Labels: bug
